---
- name: '{{ ansible_name_module }} | file | Create Directory Structure' 
  file:
    path: '{{ item }}'
    state: directory
    mode: '0644'
  with_items:
    - '{{ dir_deploy }}/secrets/registry/ssl'
    - '{{ dir_deploy }}/secrets/registry/auth'
    - '{{ dir_deploy }}/secrets/ssh'
    - '{{ dir_deploy }}/terraform'
    - '{{ dir_deploy }}/ansible'
    - '{{ dir_deploy }}/mirror'
    - '{{ dir_deploy }}/images'
    - '{{ dir_deploy }}/nginx'

- name: '{{ ansible_name_module }} | template | Stage CloudCtl Startup Assets' 
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items:
    - { mode: '0775', src: '{{ dir_koffer }}/templates/bin/start-cloudctl.sh.j2', dest: '/tmp/start-cloudctl.sh' }
    - { mode: '0655', src: '{{ dir_koffer }}/templates/pod/cloudctl.yml.j2', dest: '/tmp/cloudctl.yml' }
    - { mode: '0655', src: '{{ dir_koffer }}/templates/registry/etc-docker-registry-config.yml.j2', dest: '/root/deploy/mirror/config.yml' }


