---
- name: ocp4-deploy | post-config | Create /home/core/.kube directory 
  file:
    state: directory
    path: /home/core/.kube
    mode: 0700
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
  when: inventory_hostname in groups['workstation']

- name: ocp4-deploy | post-config | Make kubeconfig available
  copy:
    src: "{{ artifact_directory }}/bak/auth/kubeconfig"
    dest: /home/core/.kube/kubeconfig
    owner: core
    group: core
    mode: 0700
  when: inventory_hostname in groups['workstation']

- name: ocp4-deploy | post-config | Create /home/core/.kube directory on the bastion
  file:
    state: directory
    path: /home/core/.kube
    mode: 0700
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
  when: inventory_hostname in groups['bastion']

- name: ocp4-deploy | post-config | Move config file 
  copy:
    src: /home/core/.kube/kubeconfig
    dest: /home/core/.kube/config
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
  when: inventory_hostname in groups['bastion']

- name: ocp4-deploy | post-config | Remove the directory from workstation
  file:
    state: absent
    path: /home/core/.kube/
  when: inventory_hostname in groups['workstation']
